version: '3.3'

services:
   db:
     image: mymysql:v01
     ports:
       - "3306:3306"
     volumes:
       - type: volume
         source: dbdata
         target: /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: mywp:v01
     ports:
       - "8080:80"
     volumes:
       - type: volume
         source: wpconfig
         target: /etc/wordpress/
       - type: volume
         source: wpuploads
         target: /var/www/html/wp-content/uploads/
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    dbdata:
    wpconfig:
    wpuploads: