version: '3.3'

services:
   db:
     image: mymysql:v01
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: mywp:v01
     ports:
       - "8080:80"
     restart: always
volumes:
    db_data: {}